import { randomUUID } from 'node:crypto';
import { expect, test } from '@playwright/test';
import { loginBuyer } from './fixtures';

test('Покупатель изменяет свой объект: отмена, ошибка, повторное сохранение и перезагрузка', async ({ page }) => {
  const name = `E2E редактирование ${randomUUID()}`;
  const address = 'Астрахань, ул. Савушкина, 6';
  const updatedName = `${name} обновлён`;
  const updatedAddress = 'Астрахань, ул. Татищева, 18';
  await page.goto('/projects');
  await loginBuyer(page);
  await page.getByRole('button', { name: 'Новый объект', exact: true }).click();
  const create = page.getByRole('dialog', { name: 'Новый объект', exact: true });
  await create.getByLabel('Название', { exact: true }).fill(name);
  await create.getByLabel('Адрес', { exact: true }).fill(address);
  await create.getByRole('button', { name: 'Создать объект', exact: true }).click();
  await expect(create).toBeHidden();
  await page.getByRole('link').filter({ has: page.getByRole('heading', { name, exact: true }) }).click();
  await expect(page).toHaveURL(/\/projects\/[0-9a-f-]+$/);
  const id = new URL(page.url()).pathname.split('/').at(-1)!;
  const path = `/api/v1/projects/${id}`;
  const productsResponse = await page.request.get('/api/v1/products?inStock=true&limit=100');
  expect(productsResponse.ok()).toBe(true);
  const products = (await productsResponse.json()).items;
  expect(products.length).toBeGreaterThan(0);
  const product = products[0];
  await page.getByRole('button', { name: 'Добавить материал', exact: true }).click();
  const add = page.getByRole('dialog', { name: 'Добавить материал', exact: true });
  await expect(add.getByRole('combobox', { name: 'Товар', exact: true }).locator(`option[value="${product.id}"]`)).toHaveCount(1);
  await add.getByRole('combobox', { name: 'Товар', exact: true }).selectOption(product.id);
  await add.getByLabel('Количество', { exact: true }).fill('2');
  await add.getByLabel('К этапу', { exact: true }).fill('2030-01-02');
  await add.getByRole('button', { name: 'Добавить в перечень', exact: true }).click();
  await expect(add).toBeHidden();
  const need = page.locator('.needs-list .need-row');
  await expect(need).toHaveCount(1);
  await expect(need).toContainText(product.name);
  await expect(need).toContainText(`2 ${product.unit}`);
  await expect(need).toContainText('К этапу 2030-01-02');
  const beforeResponse = await page.request.get(path);
  expect(beforeResponse.ok()).toBe(true);
  const before = await beforeResponse.json();
  expect(before.items).toHaveLength(1);
  expect(before.items[0]).toMatchObject({ productId: product.id, quantity: 2, stageDate: '2030-01-02' });
  const trigger = page.getByRole('button', { name: 'Изменить объект', exact: true });
  const dialog = page.getByRole('dialog', { name: 'Изменить объект', exact: true });
  await trigger.click();
  await expect(dialog.getByLabel('Название', { exact: true })).toBeFocused();
  await expect(dialog.getByLabel('Название', { exact: true })).toHaveValue(name);
  await expect(dialog.getByLabel('Адрес', { exact: true })).toHaveValue(address);
  await expect(dialog.getByLabel('Название', { exact: true })).toHaveAttribute('maxlength', '150');
  await expect(dialog.getByLabel('Адрес', { exact: true })).toHaveAttribute('maxlength', '300');
  await dialog.getByLabel('Название', { exact: true }).fill('Отменённое название');
  await dialog.getByLabel('Адрес', { exact: true }).fill('Отменённый адрес');
  await dialog.getByRole('button', { name: 'Отмена', exact: true }).click();
  await expect(dialog).toBeHidden();
  await expect(trigger).toBeFocused();
  expect(await (await page.request.get(path)).json()).toEqual(before);
  await trigger.click();
  await expect(dialog.getByLabel('Название', { exact: true })).toHaveValue(name);
  await dialog.getByLabel('Название', { exact: true }).fill('   ');
  await dialog.getByRole('button', { name: 'Сохранить изменения', exact: true }).click();
  await expect(dialog.getByRole('alert')).toContainText('Поля не могут состоять только из пробелов');
  await page.keyboard.press('Escape');
  await expect(dialog).toBeHidden();
  await expect(trigger).toBeFocused();
  expect(await (await page.request.get(path)).json()).toEqual(before);

  await trigger.click();
  await dialog.getByLabel('Название', { exact: true }).fill(updatedName);
  await dialog.getByLabel('Адрес', { exact: true }).fill(updatedAddress);
  // Только первый PATCH прерывается: создание, повторное сохранение и GET используют настоящий API.
  await page.route(`**${path}`, async route => {
    if (route.request().method() === 'PATCH') await route.abort('failed');
    else await route.continue();
  }, { times: 1 });
  await dialog.getByRole('button', { name: 'Сохранить изменения', exact: true }).click();
  await expect(dialog.getByRole('alert')).toContainText('Не удалось сохранить объект');
  await expect(dialog.getByLabel('Название', { exact: true })).toHaveValue(updatedName);
  await expect(dialog.getByLabel('Адрес', { exact: true })).toHaveValue(updatedAddress);
  const saved = page.waitForResponse(response => new URL(response.url()).pathname === path && response.request().method() === 'PATCH');
  await dialog.getByRole('button', { name: 'Сохранить изменения', exact: true }).click();
  const response = await saved;
  expect(response.ok()).toBe(true);
  expect(response.request().postDataJSON()).toEqual({ name: updatedName, address: updatedAddress });
  await expect(dialog).toBeHidden();
  await expect(trigger).toBeFocused();
  await expect(page.getByRole('heading', { name: updatedName, exact: true })).toBeVisible();
  await expect(page.locator('.page-heading p')).toHaveText(updatedAddress);
  await expect(need).toHaveCount(1);
  await expect(need).toContainText(product.name);
  await expect(need).toContainText(`2 ${product.unit}`);
  await expect(need).toContainText('К этапу 2030-01-02');
  expect(await (await page.request.get(path)).json()).toEqual({ ...before, name: updatedName, address: updatedAddress });
  await page.reload();
  await expect(page.getByRole('heading', { name: updatedName, exact: true })).toBeVisible();
  await expect(page.locator('.page-heading p')).toHaveText(updatedAddress);
  await expect(need).toHaveCount(1);
  await expect(need).toContainText(product.name);
  await expect(need).toContainText(`2 ${product.unit}`);
  await expect(need).toContainText('К этапу 2030-01-02');
  const afterResponse = await page.request.get(path);
  expect(afterResponse.ok()).toBe(true);
  expect(await afterResponse.json()).toEqual({ ...before, name: updatedName, address: updatedAddress });
});
